listId: {type required: true, unique: true},
  bigCrumbCustom
  bigCrumbCustomType
  bigCrumbCustomMaxValue
  bigCrumbUserSetValue
  littleCrumb1Custom
  littleCrumb1CustomType
  littleCrumb1CustomMaxValue
  littleCrumb1UserSetValue
  littleCrumb2Custom
  littleCrumb2CustomType
  littleCrumb2CustomMaxValue
  littleCrumb2UserSetValue
  littleCrumb3Custom
  littleCrumb3CustomType
  littleCrumb3CustomMaxValue
  littleCrumb3UserSetValue
  littleCrumb4Custom
  littleCrumb4CustomType
  littleCrumb4CustomMaxValue
  littleCrumb4UserSetValue
  littleCrumb5Custom
  littleCrumb5CustomType
  littleCrumb5CustomMaxValue
  littleCrumb5UserSetValue
